// Generated by app-wabbit-dev setup. Do not edit by hand.

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

repositories {
    google()

    mavenCentral()

    maven("https://jitpack.io")
}

group = "one.wabbit"
version = "2.1.0"

plugins {
    id("com.android.kotlin.multiplatform.library")

    kotlin("multiplatform")

    kotlin("plugin.serialization")

    id("one.wabbit.acyclic")

    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")
    id("maven-publish")

    id("com.vanniktech.maven.publish")
}

mavenPublishing {
    coordinates("one.wabbit", "kotlin-web-steam", "2.1.0")
    publishToMavenCentral()
    signAllPublications()
    pom {
        name.set("kotlin-web-steam")
        description.set("kotlin-web-steam")
        url.set("https://github.com/wabbit-corp/kotlin-web-steam")
        licenses {
            license {
                name.set("GNU Affero General Public License v3.0 or later")
                url.set("https://spdx.org/licenses/AGPL-3.0-or-later.html")
            }
        }
        developers {
            developer {
                id.set("wabbit-corp")
                name.set("Wabbit Consulting Corporation")

                email.set("wabbit@wabbit.one")

            }
        }
        scm {
            url.set("https://github.com/wabbit-corp/kotlin-web-steam")
            connection.set("scm:git:git://github.com/wabbit-corp/kotlin-web-steam.git")
            developerConnection.set("scm:git:ssh://git@github.com/wabbit-corp/kotlin-web-steam.git")
        }
    }
}

val localPublishRequested =
    gradle.startParameter.taskNames.any { taskName -> "MavenLocal" in taskName }

if (localPublishRequested) {
    tasks.withType<org.gradle.plugins.signing.Sign>().configureEach {
        enabled = false
    }
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        freeCompilerArgs.add("-Xcontext-parameters")

        freeCompilerArgs.addAll(
            "-P",
            "plugin:one.wabbit.acyclic:compilationUnits=enabled",
        )

        freeCompilerArgs.addAll(
            "-P",
            "plugin:one.wabbit.acyclic:declarations=enabled",
        )

    }
    applyDefaultHierarchyTemplate()

    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
        testRuns["test"].executionTask.configure {
            jvmArgs("-ea")
        }
    }

    androidLibrary {
        namespace = "one.wabbit.web.steam"
        compileSdk = 34
        minSdk = 26
    }

    iosArm64()

    iosSimulatorArm64()

    macosArm64("hostNative")

    listOf(

        targets.getByName("iosArm64"),

        targets.getByName("iosSimulatorArm64"),

        targets.getByName("hostNative"),

    ).forEach { target ->
        (target as KotlinNativeTarget).binaries.framework {
            baseName = "WebSteam"
            isStatic = true
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("one.wabbit:kotlin-web-common:1.1.0")

                implementation("dev.whyoleg.cryptography:cryptography-core:0.5.0")

                implementation("dev.whyoleg.cryptography:cryptography-provider-optimal:0.5.0")

                implementation("io.ktor:ktor-client-core:3.3.0")

                implementation("io.ktor:ktor-client-content-negotiation:3.3.0")

                implementation("io.ktor:ktor-serialization-kotlinx-json:3.3.0")

                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.9.0")

                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")

            }

        }

        val commonTest by getting {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-test:2.3.10")

                implementation("io.ktor:ktor-client-mock:3.3.0")

            }

        }

        val jvmMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-cio:3.3.0")

            }

        }

        val androidMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-okhttp:3.3.0")

            }

        }

        val appleMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-darwin:3.3.0")

            }

        }

    }
}

val configuredVersionString = version.toString()

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks.withType<Test>().configureEach {
    jvmArgs("-ea")
}

dokka {
    moduleName.set("kotlin-web-steam")
    dokkaPublications.html {
        suppressInheritedMembers.set(true)
        failOnWarning.set(true)
    }

    dokkaSourceSets.configureEach {
        if (name == "commonMain") {
            val dokkaModuleFile = file("docs/dokka-module.md")
            if (dokkaModuleFile.exists()) {
                includes.from(dokkaModuleFile)
            }
        }

        sourceLink {
            localDirectory.set(file("src"))
            remoteUrl("https://github.com/wabbit-corp/kotlin-web-steam/tree/master/src")
            remoteLineSuffix.set("#L")
        }

    }

    pluginsConfiguration.html {
        footerMessage.set("(c) Wabbit Consulting Corporation")
    }
}
